### ISSUE TITLE
xb variatons

### ISSUE THREAD

**Issue by pfs** [pfs/TopLJets2015#48]
xb=pt(B)/pT(jet) with significantly large rate above 1

- enhanced in gen jets from pseudo-top producer (no neutrinos) - xb
- different behavior with gen jets matched to the PAT jets (neutrinos should be excluded as well however) - xbnu 
- ok when taken to the parton (if found) - xbp

![xb_inclusive](https://cloud.githubusercontent.com/assets/4624574/22997713/d54aa648-f3d3-11e6-839e-e74a1cae7138.png)
![xb_nosemilep](https://cloud.githubusercontent.com/assets/4624574/22997719/d718e96c-f3d3-11e6-95fb-82a56b4ed187.png)
![xb_semilep](https://cloud.githubusercontent.com/assets/4624574/22997720/d86cea84-f3d3-11e6-9c8d-8cdcc27b0b17.png)

In case of semi-leptonic B decays, it looks like the charged lepton is not added as a constituent of the jet by the PseudoTopProducer

E.g.
Jet matched to -5122 hadron with semi-leptonic decay
PAT genJet pT=112.948
Pseudo-top genJet pT 68.7483 GeV
Constituents list
	2112 8.3125
	-211 0.29541
	211 1.28125
	22 0.227905
	22 0.171875
	22 0.666504
	22 2.69531
	-11 44.2188 <--------- not found in pseudo-top genJet
	22 0.0456238
	22 0.0630493
	22 3.05664
	22 2.5957
	22 0.233154
	22 0.178833
	-211 6.35938
	211 4.05469
	-211 2.16602
	-3122 20.5938
	22 11.0312
	22 0.688965
	22 1.36719
	22 2.72266

@intrepid42

**Comment by pfs** [comment]
@intrepid42 Issue is solved if the dressedLeptons are not vetoed when clustering the jets @
https://github.com/intrepid42/cmssw/blob/pseudotoprivet_80x/TopQuarkAnalysis/TopEventProducers/interface/PseudoTop.hh#L75

**Comment by intrepid42** [comment]
Ups, I'm a bit surprised how hard those "soft leptons" are!

Just includiong them in the clustering is not optimal, we still need a way to tell them apart from prompt leptons.

* Add an isolation criterion (cannot be reused for boosted top then?)
* Use [PromptFinalState](http://rivet.hepforge.org/code/dev/classRivet_1_1PromptFinalState.html#details) (see [ATLAS analysis](https://rivet.hepforge.org/trac/browser/src/Analyses/ATLAS_2015_I1404878.cc#L31)). I thought this one relies heavily on the event record but it actually seems to be mostly equivalant to ask that the lepton does not have a hadron ancestor (see [here](http://rivet.hepforge.org/code/dev/classRivet_1_1Particle.html#a0edd8a5d12dca5dacf67b064cad601c1)).

I am actually happy with option 2 :)

**Comment by pfs** [comment]
Control distributions using the new tagging mode

- Find ~25% semi-leptonic B hadron decays with xb in the right place

![xb_semilep](https://cloud.githubusercontent.com/assets/4624574/23020213/4a0ee706-f446-11e6-9512-a85b5fb9ad96.png)

- Find some exclusively tagged c-jets  with softer fragmentation

![xb_xc](https://cloud.githubusercontent.com/assets/4624574/23020223/5beddefa-f446-11e6-84ac-57a6e1635906.png)

- Tau tags are also found

![xb_tau](https://cloud.githubusercontent.com/assets/4624574/23020335/dbe5985a-f446-11e6-9cf3-b4c04d3613fb.png)

included in b39c877
